/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controle.RelatorioControle;
import java.awt.Dimension;
import javassist.tools.rmi.RemoteException;
import javax.swing.JOptionPane;

/**
 *
 * @author juan
 */
public class TurmaListaForm extends javax.swing.JInternalFrame {

    private RelatorioControle relatorioControle;
    /**
     * Creates new form TurmaListaForm
     */
    public TurmaListaForm() {
        relatorioControle = new RelatorioControle();
        initComponents();
    }
    
    public void Centralizar() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    public RelatorioControle getRelatorioControle() {
        return relatorioControle;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        btnGroupOpcao = new javax.swing.ButtonGroup();
        btnGroupOrdem = new javax.swing.ButtonGroup();
        panelMenu = new javax.swing.JPanel();
        panelOpcao = new javax.swing.JPanel();
        rBtnTodasTurmas = new javax.swing.JRadioButton();
        rBtnTurmasPCD = new javax.swing.JRadioButton();
        panelOrdem = new javax.swing.JPanel();
        rBtnId = new javax.swing.JRadioButton();
        rBtnEnsino = new javax.swing.JRadioButton();
        rBtnAno = new javax.swing.JRadioButton();
        rBtnTotalAlu = new javax.swing.JRadioButton();
        rBtnNome = new javax.swing.JRadioButton();
        btnListar = new javax.swing.JButton();
        panelScroll = new javax.swing.JScrollPane();
        tabelaListaTurmas = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Listagem de Turmas");

        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelOpcao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opções de Busca"));

        btnGroupOpcao.add(rBtnTodasTurmas);
        rBtnTodasTurmas.setSelected(true);
        rBtnTodasTurmas.setText("Todas as Turmas");

        btnGroupOpcao.add(rBtnTurmasPCD);
        rBtnTurmasPCD.setText("Turmas com PCD");

        javax.swing.GroupLayout panelOpcaoLayout = new javax.swing.GroupLayout(panelOpcao);
        panelOpcao.setLayout(panelOpcaoLayout);
        panelOpcaoLayout.setHorizontalGroup(
            panelOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcaoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rBtnTodasTurmas)
                .addGap(18, 18, 18)
                .addComponent(rBtnTurmasPCD)
                .addContainerGap())
        );
        panelOpcaoLayout.setVerticalGroup(
            panelOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rBtnTodasTurmas)
                .addComponent(rBtnTurmasPCD))
        );

        panelOrdem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ordenar Tabela por:"));

        btnGroupOrdem.add(rBtnId);
        rBtnId.setSelected(true);
        rBtnId.setText("Id");

        btnGroupOrdem.add(rBtnEnsino);
        rBtnEnsino.setText("Ensino");
        rBtnEnsino.setToolTipText("");

        btnGroupOrdem.add(rBtnAno);
        rBtnAno.setText("Ano");

        btnGroupOrdem.add(rBtnTotalAlu);
        rBtnTotalAlu.setText("Total de Alunos");

        btnGroupOrdem.add(rBtnNome);
        rBtnNome.setText("Nome");

        javax.swing.GroupLayout panelOrdemLayout = new javax.swing.GroupLayout(panelOrdem);
        panelOrdem.setLayout(panelOrdemLayout);
        panelOrdemLayout.setHorizontalGroup(
            panelOrdemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdemLayout.createSequentialGroup()
                .addComponent(rBtnEnsino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rBtnTotalAlu))
            .addGroup(panelOrdemLayout.createSequentialGroup()
                .addComponent(rBtnId)
                .addGap(26, 26, 26)
                .addComponent(rBtnNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rBtnAno))
        );
        panelOrdemLayout.setVerticalGroup(
            panelOrdemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrdemLayout.createSequentialGroup()
                .addGroup(panelOrdemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnAno)
                    .addComponent(rBtnId)
                    .addComponent(rBtnNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelOrdemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rBtnEnsino)
                    .addComponent(rBtnTotalAlu)))
        );

        btnListar.setMnemonic('l');
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelOpcao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(panelOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelOpcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnListar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelScroll.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${relatorioControle.turmaTabelas}");
        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, tabelaListaTurmas);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ensino}"));
        columnBinding.setColumnName("Ensino");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${ano}"));
        columnBinding.setColumnName("Ano");
        columnBinding.setColumnClass(Long.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tamanhoTurma}"));
        columnBinding.setColumnName("Nº Alunos");
        columnBinding.setColumnClass(Integer.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${alunos}"));
        columnBinding.setColumnName("Alunos");
        columnBinding.setColumnClass(java.util.Collection.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        panelScroll.setViewportView(tabelaListaTurmas);
        if (tabelaListaTurmas.getColumnModel().getColumnCount() > 0) {
            tabelaListaTurmas.getColumnModel().getColumn(5).setMinWidth(0);
            tabelaListaTurmas.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        try {
            //Opcoes de busca
            this.rBtnTodasTurmas.setActionCommand("todas");
            this.rBtnTurmasPCD.setActionCommand("comPCD");  
            //Opcoes de ordenação
            this.rBtnId.setActionCommand("id");
            this.rBtnNome.setActionCommand("nome");
            this.rBtnAno.setActionCommand("ano");
            this.rBtnEnsino.setActionCommand("ensino");
            this.rBtnTotalAlu.setActionCommand("alunos");
            
            relatorioControle.listarTurmasOpcaoOrdem(
                    btnGroupOpcao.getSelection().getActionCommand(), 
                    btnGroupOrdem.getSelection().getActionCommand());

        } catch(RemoteException e ){
            JOptionPane.showMessageDialog(this,
                    "Erro "+e.getMessage(),
                    "Erro",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnListarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupOpcao;
    private javax.swing.ButtonGroup btnGroupOrdem;
    private javax.swing.JButton btnListar;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelOpcao;
    private javax.swing.JPanel panelOrdem;
    private javax.swing.JScrollPane panelScroll;
    private javax.swing.JRadioButton rBtnAno;
    private javax.swing.JRadioButton rBtnEnsino;
    private javax.swing.JRadioButton rBtnId;
    private javax.swing.JRadioButton rBtnNome;
    private javax.swing.JRadioButton rBtnTodasTurmas;
    private javax.swing.JRadioButton rBtnTotalAlu;
    private javax.swing.JRadioButton rBtnTurmasPCD;
    private javax.swing.JTable tabelaListaTurmas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
